// Generated by tools/embed_web_ui.py. Edit web/ and regenerate.
#pragma once
#include <Arduino.h>

static const char WEB_UI[] PROGMEM = R"THERMAL_UI(<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <meta name="theme-color" content="#10131a">
  <meta name="referrer" content="no-referrer">
  <link rel="icon" href="data:,">
  <title>ThermalCam</title>
  <style>
:root { color-scheme: dark; font-family: -apple-system, BlinkMacSystemFont, "Helvetica Neue", sans-serif; color: #f2f4f7; background: #10131a; }
* { box-sizing: border-box; }
body { margin: 0; }
main { max-inline-size: 48rem; margin-inline: auto; padding: max(1rem, env(safe-area-inset-top)) max(1rem, env(safe-area-inset-right)) max(1.5rem, env(safe-area-inset-bottom)) max(1rem, env(safe-area-inset-left)); }
header { display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: 1rem; }
h1 { font-size: 1.7rem; margin: .2rem 0; letter-spacing: -.04em; }
h2 { font-size: 1rem; margin: 0 0 1rem; }
.eyebrow { color: #b8c0cc; font-size: .75rem; letter-spacing: .08em; margin: 0; }
button, input, select { font: inherit; border-radius: .65rem; border: 1px solid #758097; background: #202733; color: inherit; min-block-size: 44px; padding: .6rem .75rem; }
button { cursor: pointer; }
:focus-visible { outline: 3px solid #fac578; outline-offset: 3px; }
#status { color: #b8c0cc; min-block-size: 1.5em; font-size: .875rem; }
#status[data-state="live"] { color: #9cddb7; }
#status[data-state="error"], .error { color: #ffbdab; }
figure { margin: 1rem 0 .5rem; }
canvas { display: block; inline-size: 100%; block-size: auto; aspect-ratio: 4 / 3; background: #07090d; border-radius: .75rem; touch-action: pan-y; }
canvas[data-stale="true"] { opacity: .45; }
figcaption, footer { color: #b8c0cc; font-size: .75rem; line-height: 1.6; }
figcaption { margin-block-start: .5rem; }
.scale { display: flex; align-items: center; gap: .75rem; color: #b8c0cc; font-size: .75rem; }
#gradient { flex: 1; block-size: .45rem; border-radius: 1rem; background: linear-gradient(90deg, #0b0a30, #722070, #cc3b42, #f49b39, #fff4bf); }
.readings { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: .75rem; margin: 1.5rem 0 .75rem; }
dt { color: #b8c0cc; font-size: .75rem; }
dd { margin: .4rem 0 0; font-size: clamp(1rem, 4.5vw, 1.8rem); font-variant-numeric: tabular-nums; }
.meta { display: flex; flex-wrap: wrap; justify-content: space-between; gap: .5rem; font-size: .75rem; color: #cbd2db; font-variant-numeric: tabular-nums; }
.controls { margin-block: 1.5rem; padding: 1rem; background: #191e28; border-radius: .75rem; }
.control-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: .75rem; margin-block-end: 1rem; }
label { font-size: .875rem; line-height: 1.5; }
select, input[type="number"] { display: block; inline-size: 100%; margin-block-start: .4rem; min-inline-size: 0; }
.checkbox { display: flex; align-items: center; gap: .65rem; min-block-size: 44px; }
input[type="checkbox"] { inline-size: 1.25rem; min-block-size: 1.25rem; margin: 0; accent-color: #fac578; }
.error, .notice { font-size: .875rem; line-height: 1.6; }
.notice { color: #fac578; }
[hidden] { display: none !important; }
@media (max-width: 340px) { .control-grid { grid-template-columns: 1fr; } }
</style>
</head>
<body>
  <main>
    <header>
      <div><p class="eyebrow">MLX90642 · 32 × 24</p><h1>ThermalCam</h1></div>
      <button id="reconnect" type="button">再接続</button>
    </header>
    <p id="status" role="status">接続しています…</p>
    <p id="demo" class="notice" hidden>デモ表示です。温度は実測値ではありません。</p>
    <figure>
      <canvas id="image" width="640" height="480" tabindex="0" role="img"
        aria-label="熱画像。タップまたは矢印キーで測定点を選択"
        aria-describedby="image-hint readings">熱画像はCanvas対応ブラウザで表示できます。</canvas>
      <figcaption id="image-hint">画像をタップすると、その位置の温度を表示します。</figcaption>
    </figure>
    <div class="scale" aria-hidden="true"><span id="scale-min">—</span><div id="gradient"></div><span id="scale-max">—</span></div>
    <dl id="readings" class="readings">
      <div><dt>最低</dt><dd id="minimum">—</dd></div>
      <div><dt>中央</dt><dd id="center">—</dd></div>
      <div><dt>最高</dt><dd id="maximum">—</dd></div>
    </dl>
    <div class="meta"><span id="picked">選択点：—</span><span id="ambient">Ta：—</span><span id="fps">0 fps</span></div>
    <section class="controls">
      <h2>表示</h2>
      <div class="control-grid">
        <label for="palette">カラー<select id="palette"><option value="iron">Iron</option><option value="gray">グレースケール</option></select></label>
        <label for="range">温度レンジ<select id="range"><option value="auto">自動</option><option value="fixed">固定</option></select></label>
      </div>
      <div id="fixed-range" class="control-grid" hidden>
        <label for="lower">下限（°C）<input id="lower" type="number" inputmode="decimal" value="20" min="-40" max="260" step="0.1" required aria-describedby="range-error"></label>
        <label for="upper">上限（°C）<input id="upper" type="number" inputmode="decimal" value="45" min="-40" max="260" step="0.1" required aria-describedby="range-error"></label>
      </div>
      <p id="range-error" class="error" role="alert" hidden></p>
      <label for="smooth" class="checkbox"><input id="smooth" type="checkbox" checked>表示をなめらかにする</label>
    </section>
    <footer>温度は元の32 × 24画素から読み取ります。補間は表示だけに適用します。</footer>
    <noscript><p class="error">表示にはJavaScriptを有効にしてください。</p></noscript>
  </main>
  <script>
"use strict";

// The firmware and the browser share the THM1 binary frame format.
(() => {
  const WIDTH = 32, HEIGHT = 24, PIXELS = WIDTH * HEIGHT, HEADER_BYTES = 20;
  function decodeFrame(buffer) {
    if (buffer.byteLength !== HEADER_BYTES + PIXELS * 2) throw new Error("フレーム長が一致しません");
    const data = new DataView(buffer);
    if ([84, 72, 77, 49].some((value, i) => data.getUint8(i) !== value) ||
        data.getUint16(4, true) !== WIDTH || data.getUint16(6, true) !== HEIGHT ||
        data.getUint16(18, true) !== 0) throw new Error("未対応のフレーム形式です");
    const pixels = new Float32Array(PIXELS);
    for (let i = 0; i < PIXELS; i++) pixels[i] = data.getInt16(HEADER_BYTES + i * 2, true) / 50;
    return { sequence: data.getUint32(8, true), capturedAtMs: data.getUint32(12, true),
      ta: data.getInt16(16, true) / 100, pixels };
  }
  function statistics(pixels) {
    let minIndex = 0, maxIndex = 0;
    for (let i = 1; i < PIXELS; i++) {
      if (pixels[i] < pixels[minIndex]) minIndex = i;
      if (pixels[i] > pixels[maxIndex]) maxIndex = i;
    }
    return { min: pixels[minIndex], max: pixels[maxIndex], minIndex, maxIndex,
      center: pixels[Math.floor(HEIGHT / 2) * WIDTH + Math.floor(WIDTH / 2)] };
  }
  function pixelAt(x, y, width, height) {
    return Math.min(HEIGHT - 1, Math.max(0, Math.floor(y / height * HEIGHT))) * WIDTH +
      Math.min(WIDTH - 1, Math.max(0, Math.floor(x / width * WIDTH)));
  }
  globalThis.ThermalFrame = Object.freeze({ WIDTH, HEIGHT, PIXELS, decodeFrame, statistics, pixelAt });
})();
</script>
  <script>
"use strict";

(() => {
  const { WIDTH, HEIGHT, PIXELS, decodeFrame, statistics, pixelAt } = ThermalFrame;
  const byId = (id) => document.getElementById(id);
  const canvas = byId("image"), context = canvas.getContext("2d");
  const rawCanvas = document.createElement("canvas");
  rawCanvas.width = WIDTH; rawCanvas.height = HEIGHT;
  const rawContext = rawCanvas.getContext("2d"), image = rawContext.createImageData(WIDTH, HEIGHT);
  const status = byId("status"), range = byId("range"), palette = byId("palette");
  const lower = byId("lower"), upper = byId("upper"), smooth = byId("smooth");
  const temperature = (value) => `${value.toFixed(1)} °C`;
  const stops = [[11, 10, 48], [114, 32, 112], [204, 59, 66], [244, 155, 57], [255, 244, 191]];
  const colors = Array.from({ length: 256 }, (_, i) => {
    const position = i / 255 * (stops.length - 1), a = Math.min(stops.length - 2, Math.floor(position));
    return stops[a].map((channel, c) => Math.round(channel + (stops[a + 1][c] - channel) * (position - a)));
  });
  let socket = null, generation = 0, reconnectTimer = null, connectTimer = null, backoff = 500;
  let frame = null, picked = Math.floor(HEIGHT / 2) * WIDTH + Math.floor(WIDTH / 2);
  let lastSequence = null, lastFrameAt = 0, lastActivityAt = 0, sensor = "waiting", stale = true;
  let fpsStart = 0, fpsFrames = 0, manualRange = [20, 45];

  function setStatus(message, state) {
    if (status.textContent !== message) status.textContent = message;
    status.dataset.state = state;
  }
  function invalidate(message) {
    stale = true;
    canvas.dataset.stale = "true";
    for (const id of ["minimum", "maximum", "center"]) byId(id).textContent = "—";
    byId("picked").textContent = "選択点：—";
    byId("ambient").textContent = "Ta：—";
    byId("fps").textContent = "0 fps";
    setStatus(message, "error");
  }
  function draw() {
    if (!frame) return;
    const stats = statistics(frame.pixels);
    let min, max;
    if (range.value === "fixed") [min, max] = manualRange;
    else {
      min = stats.min; max = stats.max;
      if (max - min < 1) { const midpoint = (min + max) / 2; min = midpoint - .5; max = midpoint + .5; }
    }
    for (let i = 0; i < PIXELS; i++) {
      const colorIndex = Math.round(Math.max(0, Math.min(1, (frame.pixels[i] - min) / (max - min))) * 255);
      const color = palette.value === "gray" ? [colorIndex, colorIndex, colorIndex] : colors[colorIndex];
      image.data.set([...color, 255], i * 4);
    }
    rawContext.putImageData(image, 0, 0);
    context.imageSmoothingEnabled = smooth.checked;
    context.imageSmoothingQuality = "high";
    context.drawImage(rawCanvas, 0, 0, canvas.width, canvas.height);
    const x = (picked % WIDTH + .5) / WIDTH * canvas.width;
    const y = (Math.floor(picked / WIDTH) + .5) / HEIGHT * canvas.height;
    context.beginPath(); context.moveTo(x - 9, y); context.lineTo(x + 9, y);
    context.moveTo(x, y - 9); context.lineTo(x, y + 9);
    context.strokeStyle = "#10131a"; context.lineWidth = 4; context.stroke();
    context.strokeStyle = "#fff"; context.lineWidth = 2; context.stroke();
    byId("scale-min").textContent = temperature(min); byId("scale-max").textContent = temperature(max);
    if (!stale) {
      byId("minimum").textContent = temperature(stats.min);
      byId("maximum").textContent = temperature(stats.max);
      byId("center").textContent = temperature(stats.center);
      byId("ambient").textContent = `Ta：${temperature(frame.ta)}`;
      byId("picked").textContent = `選択点 (${picked % WIDTH}, ${Math.floor(picked / WIDTH)})：${temperature(frame.pixels[picked])}`;
    }
  }
  function validateRange() {
    const valid = lower.validity.valid && upper.validity.valid && lower.valueAsNumber < upper.valueAsNumber;
    const invalid = range.value === "fixed" && !valid;
    byId("fixed-range").hidden = range.value !== "fixed";
    byId("range-error").hidden = !invalid;
    byId("range-error").textContent = invalid ? "−40〜260 °Cで、下限を上限より小さくしてください。直前の範囲を表示しています。" : "";
    lower.setAttribute("aria-invalid", String(invalid)); upper.setAttribute("aria-invalid", String(invalid));
    if (valid) manualRange = [lower.valueAsNumber, upper.valueAsNumber];
    draw();
  }
  for (const control of [range, lower, upper]) control.addEventListener("change", validateRange);
  for (const control of [lower, upper]) control.addEventListener("input", validateRange);
  smooth.addEventListener("change", draw);
  palette.addEventListener("change", () => {
    byId("gradient").style.background = palette.value === "gray" ? "linear-gradient(90deg, #000, #fff)" : "";
    draw();
  });
  canvas.addEventListener("click", (event) => {
    if (stale) return;
    const rect = canvas.getBoundingClientRect();
    picked = pixelAt(event.clientX - rect.left, event.clientY - rect.top, rect.width, rect.height);
    draw();
  });
  canvas.addEventListener("keydown", (event) => {
    if (stale || !["ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown"].includes(event.key)) return;
    event.preventDefault();
    const x = picked % WIDTH, y = Math.floor(picked / WIDTH);
    const dx = (event.key === "ArrowRight") - (event.key === "ArrowLeft");
    const dy = (event.key === "ArrowDown") - (event.key === "ArrowUp");
    picked = Math.max(0, Math.min(HEIGHT - 1, y + dy)) * WIDTH + Math.max(0, Math.min(WIDTH - 1, x + dx));
    draw();
  });

  function disconnect() {
    generation++;
    clearTimeout(reconnectTimer); clearTimeout(connectTimer);
    if (socket) { socket.onclose = null; socket.close(); socket = null; }
  }
  function connect() {
    disconnect();
    if (document.hidden) return;
    const attempt = generation;
    lastSequence = null; fpsStart = 0; fpsFrames = 0; lastFrameAt = 0; sensor = "waiting";
    lastActivityAt = performance.now();
    invalidate("接続しています…");
    let connection;
    try { connection = new WebSocket(`${location.protocol === "https:" ? "wss:" : "ws:"}//${location.host}/ws`); }
    catch { setStatus("接続できません。ThermalCamのWi-Fiに接続してください。", "error"); return; }
    socket = connection;
    connection.binaryType = "arraybuffer";
    connectTimer = setTimeout(() => { if (attempt === generation) connection.close(); }, 8000);
    connection.onopen = () => {
      if (attempt !== generation) return;
      clearTimeout(connectTimer);
      backoff = 500; lastActivityAt = performance.now();
      setStatus("接続済み · センサのデータを待っています", "waiting");
    };
    connection.onmessage = (event) => {
      if (attempt !== generation) return;
      lastActivityAt = performance.now();
      try {
        if (typeof event.data === "string") {
          const info = JSON.parse(event.data);
          if (info.type !== "status") return;
          sensor = info.sensor;
          byId("demo").hidden = info.demo !== true;
          if (sensor === "read_error") invalidate("センサを読み取れません。電源・SDA・SCLの接続を確認してください。");
          else if (sensor === "config_error") invalidate("センサが連続温度測定モードになっていません。");
          return;
        }
        const next = decodeFrame(event.data);
        if (next.sequence === lastSequence) return;
        lastSequence = next.sequence; frame = next; lastFrameAt = performance.now(); sensor = "ok";
        stale = false; canvas.dataset.stale = "false";
        setStatus("接続済み · ライブ表示", "live");
        if (!fpsStart) fpsStart = lastFrameAt;
        else fpsFrames++;
        if (lastFrameAt - fpsStart >= 1000) {
          byId("fps").textContent = `${(fpsFrames * 1000 / (lastFrameAt - fpsStart)).toFixed(1)} fps`;
          fpsStart = lastFrameAt; fpsFrames = 0;
        }
        draw();
      } catch (error) { invalidate(`受信エラー：${error.message}`); }
    };
    connection.onerror = () => {
      if (attempt === generation) setStatus("接続できません。給電とThermalCamのWi-Fi接続を確認してください。", "error");
    };
    connection.onclose = () => {
      if (attempt !== generation) return;
      clearTimeout(connectTimer); socket = null;
      invalidate("接続が切れました。自動で再接続します。");
      reconnectTimer = setTimeout(connect, backoff); backoff = Math.min(backoff * 2, 5000);
    };
  }
  byId("reconnect").addEventListener("click", connect);
  document.addEventListener("visibilitychange", () => {
    if (document.hidden) disconnect(); else connect();
  });
  window.addEventListener("pagehide", disconnect);
  window.addEventListener("pageshow", () => { if (!socket && !document.hidden) connect(); });
  setInterval(() => {
    if (document.hidden || !socket || socket.readyState !== WebSocket.OPEN) return;
    const now = performance.now();
    if (now - lastActivityAt > 5000) { socket.close(); return; }
    if (now - lastFrameAt > 3000 && sensor !== "read_error" && sensor !== "config_error")
      invalidate("センサの更新を待っています。画像は最後に受信したフレームです。");
  }, 1000);
  validateRange();
  connect();
})();
</script>
</body>
</html>
)THERMAL_UI";
