"""Embed the offline web UI in the Arduino sketch; no third-party tools needed."""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "firmware/wifi_camera/web_ui.h"


def build_html():
    html = (ROOT / "web/index.html").read_text(encoding="utf-8")
    for name, tag in (("style.css", "style"), ("frame.js", "script"), ("fusion.js", "script"), ("camera.js", "script"), ("viewer.js", "script")):
        source = (ROOT / "web" / name).read_text(encoding="utf-8")
        marker = f'<link rel="stylesheet" href="/{name}">' if tag == "style" else f'<script src="/{name}"></script>'
        assert html.count(marker) == 1, f"Missing or duplicate asset: {name}"
        html = html.replace(marker, f"<{tag}>\n{source}</{tag}>")
    return html


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check the committed header without writing")
    args = parser.parse_args()
    html = build_html()
    assert ')THERMAL_UI"' not in html, "Raw-string delimiter appears in web source"
    header = '// Generated by tools/embed_web_ui.py. Edit web/ and regenerate.\n#pragma once\n#include <Arduino.h>\n\nstatic const char WEB_UI[] PROGMEM = R"THERMAL_UI(' + html + ')THERMAL_UI";\n'
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != header:
            raise SystemExit("web_ui.h is stale; run uv run --no-project tools/embed_web_ui.py")
        print("Embedded web UI is up to date")
    else:
        TARGET.write_text(header, encoding="utf-8")
        print(f"Generated {TARGET.relative_to(ROOT)} ({len(html.encode('utf-8'))} HTML bytes)")


if __name__ == "__main__":
    main()
